### ISSUE TITLE
Modal params not working

### ISSUE THREAD

**Issue by Arneoldenhave** [archanger/LinkRouting#1]
Hi great package. I was working on this for a while but yours is a really nice implementation.

I did notice that when navigating to a model with parameters the parameter key is its value.

This is from your example: 

Route(path: "details/:id", builder: { param in NamedView(text: param["id"] ?? "No param")}, isModal: true) // added isModal
   
params = ["id": ":id"] instead of ["id":<actual_id>]

**Comment by archanger** [comment]
Thanks for the raised issue!

You are right. I never tested this case. Will fix it soon.

**Comment by archanger** [comment]
Should be fine now in the latest release https://github.com/archanger/LinkRouting/releases/tag/0.2.1
