### ISSUE TITLE
Navigation from Favourites to /hi/:id with params results in 404

### ISSUE THREAD

**Issue by Arneoldenhave** [archanger/LinkRouting#2]
I modified the example code a bit and ran into this issue:

`
@main
struct ExampleApp: App {
    

    
    var body: some Scene {
        WindowGroup {
            Router.tabbed(tabs: [
                TabRoute(
                    path: "/",
                    builder: { _ in HomeView() },
                    labelBuilder: { Label("Home", systemImage: "house") },
                    children: [
                        Route(path: "details", builder: { _ in NamedView(text: "Details")}),
                        Route(path: "hi/:id", builder: { _ in NamedView(text: "Details")}, isModal: true), // add parameter
                        Route(path: "modal/:id", builder: { _ in ModalRouter() // ignore this
           
                        }, isModal: true),
                    ]
                ),
                TabRoute(
                    path: "/favorites",
                    builder: { _ in FavoritesView() },
                    labelBuilder: { Label("Favorites", systemImage: "star") },
                    children: []
                )
            ])
        }
    }
}
`

`
struct FavoritesView: View {
    @Environment(Navigator.self) var navigator

    var body: some View {
        VStack(spacing: 16) {
            Button("open \"/details\"") {
                navigator.go(to: "/details")
            }
            Button("say \"/hi\"") {
                navigator.go(to: "/hi/123123") // added params
            }
            Button("open unknown page") {
                navigator.go(to: "/url/that/does/not/exist")
            }
            
            Button("open modal") { // ignore this
                navigator.go(to: "/details/123123123")
            }
        }
    }
}
`

**Comment by archanger** [comment]
Thanks for reporting the issue!

This is kinda related to the first issue you reported, so I updated the tests and the example app as well.
