### ISSUE TITLE
TabRouter requires a "/" path for one of the tabs

### ISSUE THREAD

**Issue by Arneoldenhave** [archanger/LinkRouting#4]
The TabRouter will fail If you don't set at least one path to "/" in the Tab routes.

I don't think that is desirable since not all apps have a "home" tab. Also it relies on the implicit assumption that devs will make the "home" page route "/".

Mobile TabsViews are a bit weird in their UX since there isn't a clear hierarchy of views like in a StackView where a root view makes sense.

My suggestion would be to remove the "/" requirement.

**Comment by archanger** [comment]
Indeed, it is not intentional. I probably just forgot to fix this line because the `TabNavigator` allows any path as the root path. It has been fixed in the latest release.

Thanks for reporting!
